# This file was generated by GoReleaser. DO NOT EDIT.
cask "devrocket-ecosystem" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "a730d6f11993cf23943c7c3091e303719d96ce92bd1116cf71f1b7d5776190f4"
      url "https://github.com/IsaiasUziel/devrocket-ecosystem/releases/download/v#{version}/devrocket-ecosystem_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "88e0dd54fc2a822ea890d736d04639d87d08346e0d7bdd5a36ba6da1052a3a89"
      url "https://github.com/IsaiasUziel/devrocket-ecosystem/releases/download/v#{version}/devrocket-ecosystem_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4e6c9803abc27dc7fcb0c8e39f4dca7258df1a9cbc44673c0b1c87786fda129c"
      url "https://github.com/IsaiasUziel/devrocket-ecosystem/releases/download/v#{version}/devrocket-ecosystem_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "04794c5fe38d074bf1655e5178e72ebae335735048b5ca6aacf6b1d1b781227a"
      url "https://github.com/IsaiasUziel/devrocket-ecosystem/releases/download/v#{version}/devrocket-ecosystem_linux_arm64.tar.gz"
    end
  end

  name "devrocket-ecosystem"
  desc "An opinionated terminal dev environment - Ghostty + Tmux + Neovim + Zsh"
  homepage "https://github.com/IsaiasUziel/devrocket-ecosystem"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dr-sys"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dr-sys"]
    end
  end

  # No zap stanza required

end
