# This file was generated by GoReleaser. DO NOT EDIT.
cask "devrocket-ecosystem" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "d4e0387101c42eb6d5043fa51a23356483a60fe9e6263efcd817e83f92633f06"
      url "https://github.com/IsaiasUziel/devrocket-ecosystem/releases/download/v#{version}/devrocket-ecosystem_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f01045f2414391d4f1e2c4c2f36e54619d16eb445675df480b9d76faa55eb64a"
      url "https://github.com/IsaiasUziel/devrocket-ecosystem/releases/download/v#{version}/devrocket-ecosystem_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b0e9519731e66426f99b08fe7f3f753b08f3759b5f8bcb352388b10bbf123baf"
      url "https://github.com/IsaiasUziel/devrocket-ecosystem/releases/download/v#{version}/devrocket-ecosystem_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1c37656659ebbb165cd41571c0a88feb4fda31aacb5057e1fb0fe2ef21b2004"
      url "https://github.com/IsaiasUziel/devrocket-ecosystem/releases/download/v#{version}/devrocket-ecosystem_linux_arm64.tar.gz"
    end
  end

  name "devrocket-ecosystem"
  desc "An opinionated terminal dev environment - Ghostty + Tmux + Neovim + Zsh"
  homepage "https://github.com/IsaiasUziel/devrocket-ecosystem"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dr-sys"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dr-sys"]
    end
  end

  # No zap stanza required

end
