# This file was generated by GoReleaser. DO NOT EDIT.
cask "devrocket-ecosystem" do
  version "0.4.4"

  on_macos do
    on_intel do
      sha256 "b873d5d911f3caa57d93c9da4b94c20a6c5dbdd1b5d670e56869533b3b78dc57"
      url "https://github.com/IsaiasUziel/devrocket-ecosystem/releases/download/v#{version}/devrocket-ecosystem_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0465a1be6d664c98f4466b1ade8591785c98752f5505edb5defa7f5d859a406f"
      url "https://github.com/IsaiasUziel/devrocket-ecosystem/releases/download/v#{version}/devrocket-ecosystem_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "181a49c1242dd71b0d0e10c1111ba6500dd820ae50b8b70305d81a9ba67d9b03"
      url "https://github.com/IsaiasUziel/devrocket-ecosystem/releases/download/v#{version}/devrocket-ecosystem_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ac744bf4dfc3db56d861addc0b84a1a2b82a2227f666c5e8dd296e57231f082"
      url "https://github.com/IsaiasUziel/devrocket-ecosystem/releases/download/v#{version}/devrocket-ecosystem_linux_arm64.tar.gz"
    end
  end

  name "devrocket-ecosystem"
  desc "An opinionated terminal dev environment - Ghostty + Tmux + Neovim + Zsh"
  homepage "https://github.com/IsaiasUziel/devrocket-ecosystem"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dr-sys"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dr-sys"]
    end
  end

  # No zap stanza required

end
